export const bikeBrands = [
    // Top 20
    "Trek",
    "Specialized",
    "Giant",
    "Cannondale",
    "Scott",
    "Canyon",
    "Santa Cruz",
    "Bianchi",
    "Pinarello",
    "Cervélo",
    "Orbea",
    "Merida",
    "Cube",
    "BMC (Bicycle Manufacturing Company)",
    "Colnago",
    "Yeti Cycles",
    "GT Bicycles",
    "Kona",
    "Fuji",
    "Lapierre",
    // Next 10
    "Ibis",
    "Rocky Mountain",
    "Pivot Cycles",
    "Marin Bikes",
    "Look",
    "Ridley",
    "Norco",
    "Ghost",
    "Felt",
    "Diamondback",
    // Popular in Mexico/Latam
    "Mercurio",
    "Alubike",
    "Turbo",
    // Add an option for other brands
    "Otra"
];
