export const bikeBrands = [
    "Alubike",
    "Amyet",
    "Basso",
    "Belfort",
    "Benotto",
    "Bergamont",
    "Bianchi",
    "Bimex",
    "BMC (Bicycle Manufacturing Company)",
    "BTwin",
    "Cannondale",
    "Canyon",
    "Cervélo",
    "Chop Chop",
    "Colnago",
    "Commencal",
    "Cube",
    "Decathlon",
    "Devinci",
    "Diamondback",
    "Evil",
    "Felt",
    "Forza",
    "Fuji",
    "Ghost",
    "Giacinto",
    "Giant",
    "Gravel",
    "GT Bicycles",
    "Haro",
    "Honey Whale",
    "Huffy",
    "Ibis",
    "Ironhorse",
    "Kona",
    "KRBO",
    "Kubor",
    "Lapierre",
    "Lime",
    "LIV",
    "Look",
    "Magistroni",
    "Marin Bikes",
    "Mercurio",
    "Merida",
    "Mongoose",
    "Monk",
    "My Bike Mx",
    "Neon",
    "Next",
    "Norco",
    "Novara",
    "Optimus",
    "Orbea",
    "Pinarello",
    "Pivot Cycles",
    "Raleigh",
    "Ridley",
    "Rock Rider",
    "Rocky Mountain",
    "Rouge",
    "Salsa",
    "Santa Cruz",
    "Scott",
    "SLP",
    "Specialized",
    "Speedone",
    "SUEH",
    "Sunspeed",
    "Transition",
    "Trek",
    "Turbo",
    "Van Rysel",
    "Windsor",
    "Yeti Cycles",
    "YT",
    "Zigna",
    "Otra"
];
